Fix subscripting NoneType error with single sleeper
With the update to homeassistant 2022.3(which changed from sleepyq to asyncsleepiq) I started getting these errors. My bed is a single-envelope model with only one side. The left side returns Nones for the data in this case.

2022-03-04 06:03:14 ERROR (MainThread) [homeassistant.components.sleepiq.coordinator] Unexpected error fetching REDACTED@SleepIQ data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/sleepiq/coordinator.py", line 37, in _async_update_data
    await self.client.fetch_bed_statuses()
  File "/usr/local/lib/python3.9/site-packages/asyncsleepiq/asyncsleepiq.py", line 189, in fetch_bed_statuses
    self.beds[bed_status['bedId']].sleepers[i].in_bed = bed_status[side+'Side']['isInBed']
TypeError: 'NoneType' object is not subscriptable